name: Fog Kernel Stable (Clang 15)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Kernel Source
        uses: actions/checkout@v4
        with:
          repository: AirmailTerror80/wwy_kernel_xiaomi_fog_rebase
          ref: makeine-staging
          fetch-depth: 1
          path: kernel
      - name: Install Build Essentials
        run: |
          sudo apt-get update
          sudo apt-get install -y bc build-essential flex bison libssl-dev libelf-dev clang lld llvm python3 git curl

      - name: Download ZyC Clang 15
        run: |
          mkdir toolchain
          cd toolchain
          # stable Feb 2026 release of Clang 15
          curl -LO https://github.com/ZyCromerZ/Clang/releases/download/15.0.7-20260208-release/Clang-15.0.7-20260208.tar.gz
          mkdir clang
          tar -xf Clang-15.0.7-20260208.tar.gz -C clang

      - name: Build Kernel
        run: |
          cd kernel
          export PATH=$GITHUB_WORKSPACE/toolchain/clang/bin:$PATH
          
          # 1. Setup Config
          make O=out ARCH=arm64 vendor/fog-perf_defconfig
          
          # 2. Compile
          make -j$(nproc --all) O=out \
               ARCH=arm64 \
               CC=clang \
               CLANG_TRIPLE=aarch64-linux-gnu- \
               CROSS_COMPILE=aarch64-linux-gnu- \
               CROSS_COMPILE_ARM32=arm-linux-gnueabi- \
               LLVM=1 \
               LLVM_IAS=1

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Fog-Stable-Kernel
          path: |
            kernel/out/arch/arm64/boot/Image
            kernel/out/arch/arm64/boot/Image.gz
            kernel/out/arch/arm64/boot/Image.gz-dtb
            kernel/out/arch/arm64/boot/dtbo.img
